In [1]:
import numpy as np
import sklearn.datasets as ds
import pandas as pd

In [2]:
class treeNode:
    matrix=0
    yeses=0
    nos=0
    links=[]
    
    def __init__(self,matrix,yeses,nos,num_links):
        self.matrix=matrix
        self.yeses=yeses
        self.nos=nos
        self.links= []
        
        

In [3]:
def countYes(vec):
    count = len(vec[vec[:]==1])
    return count
def countNo(vec):
    return len(vec)-countYes(vec)

#working fine

In [35]:
def countAndGetFeatures(vec1):
    d={}
    for i in range(len(vec1)):
        d[vec1[i]]=1
    count=len(d)
    arr=[]
    for i in d:
        arr.append(i)
    return [count,arr]


'''vec=np.array ([1,2,3,4,1,1,1])
print countAndGetFeatures(vec)'''
#count and get Features code is working fine

def getMaxYesorNo(Matrix):
    N=Matrix.shape[1]
    M=len(Matrix)
    X=len(Matrix[Matrix[:,N-1]==0])
    return max(X,M-X)

'''M = np.array([[1, 2 , 0, 0], [0, 3, 1, 1], [1, 2, 2, 1], [1, 2, 1,1]])
getMaxYesorNo(M)
'''
#Get Max Yes or No is working fine

'M = np.array([[1, 2 , 0, 0], [0, 3, 1, 1], [1, 2, 2, 1], [1, 2, 1,1]])\ngetMaxYesorNo(M)\n'

In [ ]:
''' This is extra added code after everything else is working fine'''

In [5]:
def decideFeature(Matrix,isUsed,infoRoot):
    ret_i=0.0
    largest_acc=0.0
    N=Matrix.shape[1]
    for i in range(N-1):
        Sum=0.0
        if(isUsed[i]): continue
        count,features=countAndGetFeatures(Matrix[:,i])
        for j in range(len(features)):
            tempMatrix=Matrix[Matrix[:,i]==features[j]]
            Sum+=getMaxYesorNo(tempMatrix)  #represents prediction on that value
        acc=(Sum/count)#formula for the accuracy
        if largest_acc<acc:
            largest_acc=acc
            ret_i=i
    return [ret_i,largest_acc]

'''isUsed=[False,False,False]
M = np.array([[1, 2 , 0, 0], [0, 3, 1, 1], [1, 2, 2, 1], [1, 2, 1, 0]])
print decideFeature(M,isUsed)'''

print 'working successfully'
#this is awesome that decide Features is also working fine


working successfully


In [6]:
def checkPure(Matrix):
    flag=0
    N=Matrix.shape[1]
    C=Matrix[:,N-1]
    flag=C[0]
    for i in range(len(C)):
        if C[i]!=flag:
            return False
    return True
#check pure is working fine
'''x,y=np.mgrid[0:5,0:5]
print checkPure(x)'''

'x,y=np.mgrid[0:5,0:5]\nprint checkPure(x)'

In [7]:
def isUsedAllTrue(isUsed):
    flag=0
    for i in range(len(isUsed)):
        if isUsed[i]==False:
            flag=1
            break
    if not flag:
          return True
    return False
#working fine

In [33]:
def makeDecisionTree(Matrix,isUsed):
    
    #please see the condition when isUsed is complete
    N=Matrix.shape[1]
    if(isUsedAllTrue(isUsed)):
        root=treeNode(Matrix,countYes(Matrix[:,N-1]),countNo(Matrix[:,N-1]),0)#check this, how it fits in the grand scheme of things
        return root
            
    
    if(checkPure(Matrix)):
        root=treeNode(Matrix,countYes(Matrix),countNo(Matrix),0) #0 represents there are no further links to this node
        return root #this has to be checked, since I want to return only the address of the root node and not the whole node
    
    
    #accuracy based implementation for starters
    ind,acc=decideFeature(Matrix,isUsed)
    Matrix=Matrix[Matrix[:,ind].argsort()]
    isUsed[ind]=True #check these
    
    #create a root node and populate it with the matrix
    cCount,features=countAndGetFeatures(Matrix[:,ind]) #cCount is Children Count
    
    root=treeNode(Matrix,countYes(Matrix[:,N-1]),countNo(Matrix[:,N-1]), cCount)#check this, how it fits in the grand scheme of things
    
    #call to create its children and link the children to the main root
    for j in range(cCount):
        nodeAddr=makeDecisionTree(Matrix[Matrix[:,ind]==features[j]],isUsed)
        root.links.append(nodeAddr)
    #return the base adress of this root node to the user
    return root

In [34]:
M=np.array([[1,1,1],[1,0,1],[0,1,1],[0,0,0]])

isUsed=[False,False]
root= makeDecisionTree(M,isUsed)
q=[]
q.append(root)
level=0
while len(q)!=0:
    root=q.pop()
    print 'Count of 0 = 'root.nos
    print 'Count of 1 = 'root.yeses
    print 'Current Entropy at is' 
    print
    children=(len(root.links))
    for i in range(children):
        q.append(root.links[i])
    


3 1  ----- >
[[0 1 1]
 [0 0 0]
 [1 1 1]
 [1 0 1]]

2 0  ----- >
[[1 1 1]
 [1 0 1]]

1 1  ----- >
[[0 0 0]
 [0 1 1]]

1 0  ----- >
[[0 1 1]]

0 1  ----- >
[[0 0 0]]

