In [13]:
d={}
import numpy as np

In [21]:
d[1]=1
d[1]=2
d[2]=3
d[3]=2



{1: 2, 2: 3, 3: 2}


In [17]:
M = np.array([[1, 2 , 0, 0], [0, 3, 1, 1], [1, 2, 2, 1], [1, 2, 1,1]])

In [19]:
print  M[M[:,1].argsort()]

[[1 2 0 0]
 [1 2 2 1]
 [1 2 1 1]
 [0 3 1 1]]
