In [1]:
import numpy as np
from sklearn import preprocessing

In [5]:
X,Y=np.mgrid[10:50,50:59]


In [7]:
X

array([[10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12],
       [13, 13, 13, 13, 13, 13, 13, 13, 13],
       [14, 14, 14, 14, 14, 14, 14, 14, 14],
       [15, 15, 15, 15, 15, 15, 15, 15, 15],
       [16, 16, 16, 16, 16, 16, 16, 16, 16],
       [17, 17, 17, 17, 17, 17, 17, 17, 17],
       [18, 18, 18, 18, 18, 18, 18, 18, 18],
       [19, 19, 19, 19, 19, 19, 19, 19, 19],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [21, 21, 21, 21, 21, 21, 21, 21, 21],
       [22, 22, 22, 22, 22, 22, 22, 22, 22],
       [23, 23, 23, 23, 23, 23, 23, 23, 23],
       [24, 24, 24, 24, 24, 24, 24, 24, 24],
       [25, 25, 25, 25, 25, 25, 25, 25, 25],
       [26, 26, 26, 26, 26, 26, 26, 26, 26],
       [27, 27, 27, 27, 27, 27, 27, 27, 27],
       [28, 28, 28, 28, 28, 28, 28, 28, 28],
       [29, 29, 29, 29, 29, 29, 29, 29, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30],
       [31, 31, 31, 31, 31, 31, 31, 31, 31],
       [32

In [10]:
values= preprocessing.scale(X)

In [11]:
scaler=preprocessing.StandardScaler().fit(X)

C:\Users\80LM0141IH\Anaconda3\envs\py27\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [16]:
print dir(scaler)
print scaler.mean_
print scaler.var_
print scaler.scale_ #this is indeed stdeviation
print scaler.transform(X)

['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__getstate__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_get_param_names', '_reset', 'copy', 'fit', 'fit_transform', 'get_params', 'inverse_transform', 'mean_', 'n_samples_seen_', 'partial_fit', 'scale_', 'set_params', 'transform', 'var_', 'with_mean', 'with_std']
[ 29.5  29.5  29.5  29.5  29.5  29.5  29.5  29.5  29.5]
[ 133.25  133.25  133.25  133.25  133.25  133.25  133.25  133.25  133.25]
[ 11.54339638  11.54339638  11.54339638  11.54339638  11.54339638
  11.54339638  11.54339638  11.54339638  11.54339638]
[[-1.68927752 -1.68927752 -1.68927752 -1.68927752 -1.68927752 -1.68927752
  -1.68927752 -1.68927752 -1.68927752]
 [-1.6026479  -1.6026479  -1.6026479  -1.6026479  -1.6026479  -1.6026479
  -1.6026479  -1.6026479  -1.6026479 ]
 [-1.51601829 -1.51601829 -1.5